name: Getting Started
run-name: Can you run to get the env versions?
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: sh ./github-actions-script.sh
        
      - name: Run a multi-line script
        run: |
          echo Nothing to see in the multi-line script
          echo Here is what is in the folder
          ls -a
