name: Getting Started
run-name: Can you run to get the env versions?
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, World!
        
      - name: Run a multi-line script
        run: |
          echo 1. What is in this directory?
          ls -a
          echo 
          echo 2. Is Java installed?
          java -version
          echo
          echo 3. Is Git installed?
          git --version
          echo
          echo 4. What about the build tools?
          mvn --version
          gradle --version
          ant -version
          echo
          echo 5. Where is the Android SDK Root?
          echo $ANDROID_SDK_ROOT
          echo
          echo 6. Where is the Selenium jars?
          echo $SELENIUM_JAR_PATH
          echo
          echo 7. What is the workspace location?
          echo $RUNNER_WORKSPACE
          echo
          echo 8. Who is running the script?
          whoami
          echo
          echo 9. How is the disc laid out?
          df
          echo
          echo 10. What environment variables are available?
          env
          echo
          echo 11. Is node installed?
          node -v
          echo
          echo 12. And the npm version?
          npm -v
          echo
