name: Basic Workflow Dispatch Example

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Deploying the basic workflow dispatch!!!"
        - run: echo "${{github.ref_type}}"
        - run: echo "${{github.ref_name}}"

