name: Basic Workflow Dispatch Example

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Deploying the basic workflow dispatch!!!"
        - run: echo "${{github.ref_type}}"
        - run: echo "${{github.ref_name}}"
        - run: echo "${{github}}"
        - run: echo "${{github.action}}"
        - run: echo "${{github.action_path}}"
        - run: echo "${{github.repository}}"
        - run: echo "${{github.workflow}}"
        - run: echo "${{github.ref}}"
        - run: echo "${{github.base_ref}}"
        - run: echo "Current branch is ${GITHUB_REF#refs/heads/}"


