name: Dynamic Deploy

run-name: Deploy to environment - ${{github.event.inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select a target environment to deploy
        options:
        - Sandbox
        - Production

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to ${{github.event.inputs.environment}}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Tag: ${{ github.ref }}"
  deploy-to-sandbox:
    needs: logs
    runs-on: ubuntu-latest
    if: (github.ref_type == 'tag' && github.event.inputs.environment == 'Sandbox')
    steps:
      - run: |
          echo "Deploying to Sandbox : ${{github.event.inputs.environment}}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Tag: ${{ github.ref }}"
  
  deploy-to-production:
    needs: logs
    runs-on: ubuntu-latest
    if: (github.ref_type == 'tag' && github.event.inputs.environment == 'Production')
    steps:
      - run: |
          echo "Deploying to Production : ${{github.event.inputs.environment}}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Tag: ${{ github.ref }}"
