name: Dynamic Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select a target environment to deploy
        options:
        - Sandbox
        - Production

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to ${{github.event.inputs.environment}}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Tag: ${{ github.ref }}"
  deploy-to-sandbox:
    needs: logs
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'Sandbox' }}
    steps:
      - run: |
          echo "Deploying to Sandbox"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Tag: ${{ github.ref }}"
  
  deploy-to-production:
    needs: logs
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'Production' }}
    steps:
      - run: |
          echo "Deploying to Production"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Tag: ${{ github.ref }}"
