name: Starter workflow

on:
  workflow_dispatch:

jobs:
  # call-workflow-in-local-repo:
  #   uses: ./.github/workflows/reusable-wf.yml
  MTS_Schema_Validation_QA:
    uses: ./.github/workflows/postman-collections.yml
